version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: tsvetokraft
      POSTGRES_USER: tsvetokraft
      POSTGRES_PASSWORD: tsvetokraft
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://tsvetokraft:tsvetokraft@db:5432/tsvetokraft
      # Добавьте другие переменные окружения по необходимости
    ports:
      - "5000:5000"
    volumes:
      - ./attached_assets:/app/attached_assets
    command: ["node", "dist/index.js"]

volumes:
  pgdata: